name: Main

on:
  push:
    branches: ["main"]

jobs:
  check-and-deploy-main:
    name: Check and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency: templates-check-and-deploy-main
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      TEMPLATES_API_CLIENT_ID: ${{ secrets.TEMPLATES_API_CLIENT_ID }}
      TEMPLATES_API_CLIENT_SECRET: ${{ secrets.TEMPLATES_API_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - run: pnpm -w check
      - run: pnpm -w test
      - run: pnpm run deploy # pnpm deploy is a whole other thing apparently
