# Read this before modifying this file: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/

name: PullRequests

on:
  pull_request_target:
    types: ["opened", "reopened", "synchronize"]

permissions:
  pull-requests: write

env:
  PREVIEW_DIR: "_preview-templates"

jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-preview
      cancel-in-progress: true
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        #
        # Note: Checking out the source of the PR means checking out untrusted code.
        # We shouldn't run any tests or packge installs past this point.
        # Simply checking out to fetch the files is reasonable, however.
        # https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
        #
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.sha }}
          path: $PREVIEW_DIR
      - run: |
          pnpm -w preview $PREVIEW_DIR \
            --repoFullName ${{ github.event.pull_request.head.repo.full_name }} \
            --branch ${{ github.event.pull_request.head.sha }} \
            --pr ${{ github.event.pull_request.number }}
