name: "Release"

on:
  release:
    types:
      - released

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-upload
      cancel-in-progress: true
    steps:
      - uses: ./.github/actions/setup

      - name: Make templates live and publicly accessible in the dash
        run: |
          pnpm run upload . \
            --repoFullName ${{ github.repository }} \
            --branch ${{ github.sha }}
